---
# tasks file for mytom7DeployOnRedHat
- name: my  war  files delete
  file:
    path: /usr/share/tomcat/webapps/{{ item }}
    state: absent
  with_items:
    - SKRLogin-1.0
    - SKRLogin-1.0.war
  when: ansible_os_family =="RedHat"




- name: Download the war file and keep in webapps folder
  get_url:
    url:  http://18.136.193.17:8081/artifactory/test/{{ buildnoo }}/target/SKRLogin-1.0.war
    dest:  /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: restarttom7
  when: ansible_os_family =="RedHat"
