---
# tasks file for mytom7DeployOnRedHat
- name: my  war  files delete
  file:
    path: /usr/share/tomcat/webapps/{{ item }}
    state: absent
  with_items:
    - gameoflife
    - gameoflife.war
  when: ansible_os_family =="RedHat"




- name: Download the war file and keep in webapps folder
  get_url:
    url: http://52.221.204.209:8081/artifactory/SKRSIT/5/gameoflife-web/target/gameoflife.war
    dest:  /usr/share/tomcat/webapps/
    force_basic_auth: yes
  notify: restarttom7
  when: ansible_os_family =="RedHat"
