---
- hosts: webserver
  become: yes
  tasks:
  - name: install java7 on redhat
    yum:
      name: "{{ javaversion7_redhat }}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: install java7 on ubuntu
    apt:
      name: "{{ javaversion7_ubuntu }}"
      state: present
    when: ansible_os_family =="Debian"