---
- hosts: mywebservers
  become: yes
  tasks:
  - include_tasks: myfiel.yml
  - name: install webserver on redhat
    yum:
      name: httpd
      state: present
    notify: starthttpd
    when: ansible_os_family =="RedHat"
     
  - name: copy the index file from cm to all redhat nodes
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: starthttpd
    when: ansible_os_family =="RedHat"


  handlers:
  - name: starthttpd 
    service:
      name: httpd
      state: started
      