---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on redhat(httpd)
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"

  - name: isntall webser on ubuntu(apache2)
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"