---
# tasks file for tom7deploy

- name: deploy war on the webapp folder
  get_url:
    url: https://s3-ap-southeast-1.amazonaws.com/maha4iac/SKRlogin.war
    dest: /usr/share/tomcat/webapps/SKRlogin.war
    force_basic_auth: yes
    notify: restarttomcatd
  when: ansible_os_family =="RedhatL"
